//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vulcanova.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vulcanova.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        internal static string AddAccountLabel {
            get {
                return ResourceManager.GetString("AddAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter below values from &apos;Dodaj konto&apos; section from the web diary client.
        /// </summary>
        internal static string AddAccountSubheadingLabel {
            get {
                return ResourceManager.GetString("AddAccountSubheadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        internal static string EnterPinCodeLabel {
            get {
                return ResourceManager.GetString("EnterPinCodeLabel", resourceCulture);
            }
        }
        
        internal static string EnterPinCodeSubheadingLabel {
            get {
                return ResourceManager.GetString("EnterPinCodeSubheadingLabel", resourceCulture);
            }
        }
        
        internal static string QrScannerViewTitle {
            get {
                return ResourceManager.GetString("QrScannerViewTitle", resourceCulture);
            }
        }
        
        internal static string LuckyNumberTabTitle {
            get {
                return ResourceManager.GetString("LuckyNumberTabTitle", resourceCulture);
            }
        }
        
        internal static string GradesTabTitle {
            get {
                return ResourceManager.GetString("GradesTabTitle", resourceCulture);
            }
        }
        
        internal static string GradeWeightLabel {
            get {
                return ResourceManager.GetString("GradeWeightLabel", resourceCulture);
            }
        }
        
        internal static string GradeCreatedDateLabel {
            get {
                return ResourceManager.GetString("GradeCreatedDateLabel", resourceCulture);
            }
        }
        
        internal static string GradeModifiedDateLabel {
            get {
                return ResourceManager.GetString("GradeModifiedDateLabel", resourceCulture);
            }
        }
        
        internal static string GradeEmptyNameLabel {
            get {
                return ResourceManager.GetString("GradeEmptyNameLabel", resourceCulture);
            }
        }
        
        internal static string PartialGradesTabTitle {
            get {
                return ResourceManager.GetString("PartialGradesTabTitle", resourceCulture);
            }
        }
        
        internal static string FinalGradesTabTitle {
            get {
                return ResourceManager.GetString("FinalGradesTabTitle", resourceCulture);
            }
        }
        
        internal static string ErrorInvalidToken {
            get {
                return ResourceManager.GetString("ErrorInvalidToken", resourceCulture);
            }
        }
        
        internal static string PredictedGradeLabel {
            get {
                return ResourceManager.GetString("PredictedGradeLabel", resourceCulture);
            }
        }
        
        internal static string FinalGradeLabel {
            get {
                return ResourceManager.GetString("FinalGradeLabel", resourceCulture);
            }
        }
        
        internal static string NoElementsLabel {
            get {
                return ResourceManager.GetString("NoElementsLabel", resourceCulture);
            }
        }
        
        internal static string NoPredictedGradesLabel {
            get {
                return ResourceManager.GetString("NoPredictedGradesLabel", resourceCulture);
            }
        }
        
        internal static string NoLessonsLabel {
            get {
                return ResourceManager.GetString("NoLessonsLabel", resourceCulture);
            }
        }
        
        internal static string NoExamsLabel {
            get {
                return ResourceManager.GetString("NoExamsLabel", resourceCulture);
            }
        }
        
        internal static string TimetableTabTitle {
            get {
                return ResourceManager.GetString("TimetableTabTitle", resourceCulture);
            }
        }
        
        internal static string NoLuckyNumber {
            get {
                return ResourceManager.GetString("NoLuckyNumber", resourceCulture);
            }
        }
        
>>>>>>> a4399efbb78d86386440da978a8db54587ec9c77
        internal static string AttendanceTabTitle {
            get {
                return ResourceManager.GetString("AttendanceTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter PIN code.
        /// </summary>
        internal static string EnterPinCodeLabel {
            get {
                return ResourceManager.GetString("EnterPinCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To finish adding account, enter the PIN code.
        /// </summary>
        internal static string EnterPinCodeSubheadingLabel {
            get {
                return ResourceManager.GetString("EnterPinCodeSubheadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API url found for given token.
        /// </summary>
        internal static string ErrorInvalidToken {
            get {
                return ResourceManager.GetString("ErrorInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exams.
        /// </summary>
        internal static string ExamsTabTitle {
            get {
                return ResourceManager.GetString("ExamsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final grade.
        /// </summary>
        internal static string FinalGradeLabel {
            get {
                return ResourceManager.GetString("FinalGradeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final grades.
        /// </summary>
        internal static string FinalGradesTabTitle {
            get {
                return ResourceManager.GetString("FinalGradesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulcanova on GitHub.
        /// </summary>
        internal static string GitHubLinkLabel {
            get {
                return ResourceManager.GetString("GitHubLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date: {0:d}.
        /// </summary>
        internal static string GradeCreatedDateLabel {
            get {
                return ResourceManager.GetString("GradeCreatedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to untitled.
        /// </summary>
        internal static string GradeEmptyNameLabel {
            get {
                return ResourceManager.GetString("GradeEmptyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (modified: {0:d}).
        /// </summary>
        internal static string GradeModifiedDateLabel {
            get {
                return ResourceManager.GetString("GradeModifiedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades.
        /// </summary>
        internal static string GradesTabTitle {
            get {
                return ResourceManager.GetString("GradesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weight: {0}.
        /// </summary>
        internal static string GradeWeightLabel {
            get {
                return ResourceManager.GetString("GradeWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homeworks.
        /// </summary>
        internal static string HomeworksTabTitle {
            get {
                return ResourceManager.GetString("HomeworksTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string LessonDateLabel {
            get {
                return ResourceManager.GetString("LessonDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string LessonSubjectLabel {
            get {
                return ResourceManager.GetString("LessonSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        internal static string LessonTeacherLabel {
            get {
                return ResourceManager.GetString("LessonTeacherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string LessonTimeLabel {
            get {
                return ResourceManager.GetString("LessonTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:HH:mm} – {1:HH:mm}, Lesson {2}.
        /// </summary>
        internal static string LessonTimeValueLabel {
            get {
                return ResourceManager.GetString("LessonTimeValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky number.
        /// </summary>
        internal static string LuckyNumberTabTitle {
            get {
                return ResourceManager.GetString("LuckyNumberTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Attendance.
        /// </summary>
        internal static string NoAttendanceLabel {
            get {
                return ResourceManager.GetString("NoAttendanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No elements.
        /// </summary>
        internal static string NoElementsLabel {
            get {
                return ResourceManager.GetString("NoElementsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No predicted grades have been added or the register does not provide such data.
        /// </summary>
        internal static string NoPredictedGradesLabel {
            get {
                return ResourceManager.GetString("NoPredictedGradesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial grades.
        /// </summary>
        internal static string PartialGradesTabTitle {
            get {
                return ResourceManager.GetString("PartialGradesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted grade.
        /// </summary>
        internal static string PredictedGradeLabel {
            get {
                return ResourceManager.GetString("PredictedGradeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Scanner.
        /// </summary>
        internal static string QrScannerViewTitle {
            get {
                return ResourceManager.GetString("QrScannerViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR code.
        /// </summary>
        internal static string ScanQrCodeButton {
            get {
                return ResourceManager.GetString("ScanQrCodeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter data manually.
        /// </summary>
        internal static string SignInManuallyButton {
            get {
                return ResourceManager.GetString("SignInManuallyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable.
        /// </summary>
        internal static string TimetableTabTitle {
            get {
                return ResourceManager.GetString("TimetableTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unofficial Vulcan UONET+ mobile client.
        /// </summary>
        internal static string VulcanovaSubheadingLabel {
            get {
                return ResourceManager.GetString("VulcanovaSubheadingLabel", resourceCulture);
            }
        }
        
        internal static string ExamsSubjectLabel {
            get {
                return ResourceManager.GetString("ExamsSubjectLabel", resourceCulture);
            }
        }
        
        internal static string ExamsCreatorLabel {
            get {
                return ResourceManager.GetString("ExamsCreatorLabel", resourceCulture);
            }
        }
        
        internal static string ExamsDeadlineLabel {
            get {
                return ResourceManager.GetString("ExamsDeadlineLabel", resourceCulture);
            }
        }
        
        internal static string ExamsTypeLabel {
            get {
                return ResourceManager.GetString("ExamsTypeLabel", resourceCulture);
            }
        }
        
        internal static string ExamsCommentLabel {
            get {
                return ResourceManager.GetString("ExamsCommentLabel", resourceCulture);
            }
        }
        
        internal static string ExamsCreatedOnLabel {
            get {
                return ResourceManager.GetString("ExamsCreatedOnLabel", resourceCulture);
            }
        }
        
        internal static string SettingsTabTitle {
            get {
                return ResourceManager.GetString("SettingsTabTitle", resourceCulture);
            }
        }
        
        internal static string SettingsViewGradesSection {
            get {
                return ResourceManager.GetString("SettingsViewGradesSection", resourceCulture);
            }
        }
        
        internal static string GradesSettingsValueOfPlus {
            get {
                return ResourceManager.GetString("GradesSettingsValueOfPlus", resourceCulture);
            }
        }
        
        internal static string GradesSettingsValueOfMinus {
            get {
                return ResourceManager.GetString("GradesSettingsValueOfMinus", resourceCulture);
            }
        }
        
        internal static string SettingsCustomValueLabel {
            get {
                return ResourceManager.GetString("SettingsCustomValueLabel", resourceCulture);
            }
        }
        
        internal static string SettingsCustomOptionText {
            get {
                return ResourceManager.GetString("SettingsCustomOptionText", resourceCulture);
            }
        }
    }
}
